config/routes.rb
Papercup::Application.routes.draw do
  devise_for :users 
  resources :prompts

  root :to => "pages#index"

  get "/index", controller:"pages",action: :index, as: :index
  get "/refresh_image", controller: "pages", action: :refresh_image, as: :refresh_image

end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :prompts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  def index
    require "rubygems"
    require "twitter"
    # @tweets = Tweet.all

    # Certain methods require authentication. To get your Twitter OAuth credentials,
    # register an app at http://dev.twitter.com/apps

    #client = Twitter::Streaming::Client.new do |config|
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = '390u60XsK2NT1HhFTBfa7g'
      config.consumer_secret =  '36PgMnKr8Ij0oF2KGNSeF53eLxKbrF1va1mJNL3Y'
      config.oauth_token = '565043575-jHvcgBllfPWFtb5zBcWJqu3B0tq1ghNkbKiAkP3E'
      config.oauth_token_secret = 'xIxKyk6SRWnGct4frB0tIKBuIKNQrb6VBLZT44aK3LuBO'
    end

    @arrayOfTweets = []
    # client.search("to:justinbieber marry me", :count => 3, :result_type => "recent").take(3).collect do |object|
    client.search("life", :count => 20, :result_type => "recent").take(20).collect do |object|
      @arrayOfTweets <<  object.text if object.is_a?(Twitter::Tweet)  
    end


    require "flickraw"

    FlickRaw.api_key="49be9cfc544528589df1dfa4d7878c6b"
    FlickRaw.shared_secret="737b50330524d349"

    @list  = flickr.photos.getRecent

    id     = @list[0].id
    secret = @list[0].secret
    info = flickr.photos.getInfo :photo_id => id, :secret => secret
    
    url=params[:url]
    @embed_photo={}
    @embed_photo['flickr']=FlickRaw.url(info)

    puts info.title           # => "PICT986"
    puts info.dates.taken     # => "2006-07-06 15:16:18"

    sizes = flickr.photos.getSizes :photo_id => id

    original = sizes.find {|s| s.label == 'Original' }
    #puts original.width       # => "800" -- may fail if they have no original marked image
  

    require "ruby_reddit_api"
    r = Reddit::Api.new "acontero", "lalala"
    @results = r.browse "funny"  
  end

  def refresh_image
    redirect_to root_path
  end



end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_action :set_prompt, only: [:show, :edit, :update, :destroy]
  # skip_before_filter  :authenticate_user!, only: [:index]
  
  # GET /prompts
  # GET /prompts.json
  def index
    @prompts = Prompt.all
  end

  # GET /prompts/1
  # GET /prompts/1.json
  def show
  end

  # GET /prompts/new
  def new
    @prompt = Prompt.new
  end

  # GET /prompts/1/edit
  def edit
  end

  # POST /prompts
  # POST /prompts.json
  def create
    @prompt = Prompt.new(prompt_params)
    # @prompt.user = current_user
    
    respond_to do |format|
      if @prompt.save
        format.html { redirect_to @prompt, notice: 'Prompt was successfully created.' }
        format.json { render action: 'show', status: :created, location: @prompt }
      else
        format.html { render action: 'new' }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prompts/1
  # PATCH/PUT /prompts/1.json
  def update
    respond_to do |format|
      if @prompt.update(prompt_params)
        format.html { redirect_to @prompt, notice: 'Prompt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1
  # DELETE /prompts/1.json
  def destroy
    @prompt.destroy
    respond_to do |format|
      format.html { redirect_to prompts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      @prompt = Prompt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prompt_params
      params.require(:prompt).permit(:name,:notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

   
  
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%=root_path%>">Paper Cup</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- <li><a href="users/sign_in">Login</a></li> -->
            <% if user_signed_in? %>
            <li><%= link_to "Ideas Log", "/prompts" %></li>
            <% end %>
            <!-- <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<div class="container">

    <li class="nav pull-right">   
          <div id="user_nav">
            <% if user_signed_in? %>
            Signed in as <%= current_user.email %>. Not you?  
            <%= link_to "Sign out", destroy_user_session_path, :method=>:delete, :class => 'btn btn-danger btn-mini active' %>
            <% else %>
            <%= link_to new_user_registration_path do %>
            <button class="btn-mini btn btn-info">Sign Up</button>
            <% end %>
            or <%= link_to new_user_session_path do %>
            <button class="btn btn-info btn-mini">Sign In</button>
            <% end %>
            <% end %>
          </div>
        </li>


<%= yield %>

<br>

<footer>
        <p>&copy; Paper Cup 2014</p>
      </footer>
</div>



</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--     <title><%= content_for?(:title) ? yield(:title) : "Paper Cup" %></title> -->
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

   
  
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%=root_path%>">Paper Cup</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
           <!--  <li><a href="users/sign_in">Login</a></li> -->
            <% if user_signed_in? %>
            <li><%= link_to "Ideas Log", "/prompts" %></li>
            <% end %>
            <!-- <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    

<div class="container">

<li class="nav pull-right">   
          <div id="user_nav">
            <% if user_signed_in? %>
            Signed in as <%= current_user.email %>. Not you?  
            <%= link_to "Sign out", destroy_user_session_path, :method=>:delete, :class => 'btn btn-danger btn-mini active' %>
            <% else %>
            <%= link_to new_user_registration_path do %>
            <button class="btn-mini btn btn-info">Sign Up</button>
            <% end %>
            or <%= link_to new_user_session_path do %>
            <button class="btn btn-info btn-mini">Sign In</button>
            <% end %>
            <% end %>
          </div>
        </li>

<h1>Paper Cup</h1>
<h3>A social-media-derived writing inspiration generator</h3>

<h2>From Flickr</h2>
<embed src=<%=@embed_photo["flickr"]%> width=”375″ height=”225″ /><br/>

<h2>From Twitter</h2>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% 3.times do |i| %>
      <tr>
        <td><%= @arrayOfTweets[i] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>From Reddit</h2>
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% 3.times do |i| %>
      <tr>
        <td><%= @results[i].title %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

<br>

<%= link_to refresh_image_path do %>
    <button class="btn-mini btn btn-info">Refresh</button>
<% end %>

<h2>Now get to writing!</h2>

<br>

 <footer>
        <p>&copy; Paper Cup 2014</p>
      </footer>
</div>

app/views/prompts/_form.html.erb
<%= form_for @prompt, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :notes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes, :class => 'text_area' %>
    </div>
  </div>

  <br>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                prompts_path, :class => 'btn' %>
  </div>

<% end %>

app/views/prompts/edit.html.erb
<%- model_class = Prompt -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/prompts/index.html.erb
<%- model_class = Prompt -%>
<div class="page-header">
  <h1>Ideas Log</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <!-- <th><%= model_class.human_attribute_name(:user) %></th> -->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @prompts.each do |prompt| %>
      <tr>
        <td><%= prompt.name %></td>
        <td><%= prompt.notes %></td>
       <!--  <td><%= link_to prompts.user.email if prompt.user.present?%></td> -->
        <td><%=l prompt.created_at %></td>
         <td>
          
          <%= link_to "Show", prompt_path(prompt), :class => 'btn btn-small btn-info active'%>
         
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_prompt_path(prompt), :class => 'btn btn-small btn-warning active' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      prompt_path(prompt),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-small btn-danger active' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_prompt_path,
            :class => 'btn btn-primary active' %>
<br>

app/views/prompts/new.html.erb
<%- model_class = Prompt -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model} Idea'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/prompts/show.html.erb
<%- model_class = Prompt -%>
<div class="page-header">
  <h1>Prompt Idea</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @prompt.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @prompt.notes %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.[links].back")),
              prompts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_prompt_path(@prompt), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              prompt_path(@prompt),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>